### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by phutchins** [timfpark/passport-publickey#2]
Is this project still maintained? I've noticed that the documentation is incorrect. I'd submit a PR to fix the doc but not sure if this is still maintained...

Also the link to examples is broken and I'm unable to find any examples of how this could/should be used.

If you are not maintaining this, are you looking for a new maintainer?

**Comment by timfpark** [comment]
I no longer use it in any projects -- but I'm happy to make you a maintainer if you are interested in contributing to it!

**Comment by dradux** [comment]
@timfpark , this is an interesting project, I'd like to be considered for becoming a maintainer if you can provide me with an example. I can upgrade things to current versions and add documentation/examples provided you can get me a basic/rough example to check out.

**Comment by dradux** [comment]
The process as I understand it:
- user (client) hits node and gets a nonce
- user (client) signs nonce and returns nonce and signed nonce (signature) to node
- node (server) gets user by looking up user by nonce, obtains user's public key, and uses it to verify the signature, if successful user is returned, else false.

Is this all correct or am I missing something?

**Comment by phutchins** [comment]
@timfpark awesome, I actually ended up building my own here: https://github.com/phutchins/passport-keyverify taking inspiration from your project!

Would be a shame to split efforts on having a good key verification scheme for passport. @dradux, maybe you can take a look at both and we could combine efforts to maintain one that suits our needs?

I currently use passport-keyverify in my client side encrypted chat app so it's actively used and works well. I have an example but the docs aren't fantastic... 

You can see how I currently use it here: https://github.com/phutchins/pipo/blob/master/server/js/managers/authentication.js

I'd be glad to help however makes the most sense!

**Comment by dradux** [comment]
@phutchins, did you fork? If so what changes did you make? I think it would be a shame to have multiple projects here as it will definitely confuse people. I'm willing to work on merging things and getting one instance up, available, and supported.

@timfpark, are you willing to let us use this project or would you prefer we fork/use @phutchins project?

**Comment by timfpark** [comment]
@phutchins and @dradux,

I'm happy to add you as maintainers - I will do that now...

**Comment by dradux** [comment]
Thanks @timfpark , @phutchins are you willing to merge yours back into passport-publickey?

**Comment by phutchins** [comment]
Awesome @timfpark thanks! Will be glad to help keep this one up to date as needed...

@dradux I didn't fork, but both are still very similar. I added the user parameter so that I could identify who is trying to auth. My plan is to add the logic from my example, as well as a few other use cases into the core of the project so that it doesn't take as much to implement in new projects.

If @timfpark is no longer using the project I'd lean more toward working out of my repo but either way, glad to help out however I can.

**Comment by hongkongkiwi** [comment]
It looks like neither of you are now maintaining the projects if I look at last commit date.

Are there any active projects with similar functionality?

**Comment by phutchins** [comment]
@hongkongkiwi it is still used in one of my projects. I'm using my version still however... Is there some issue that you're having with it? If it still works, it may not need changes...
